<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>OrderService.Domain</RootNamespace>
    <AssemblyName>OrderService.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="MediatR" />
  </ItemGroup>
</Project>
